# Generated by Django 2.0.2 on 2018-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recent_location_X',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_location_Y',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
